styles=css/welcome.css
import=common/keycloak

stylesCommon=node_modules/patternfly/dist/css/patternfly.css node_modules/patternfly/dist/css/patternfly-additions.css

documentationUrl=https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/
displayCommunityLinks=false